import { useRef, useState } from 'react';
import { useTheme } from '../context/ThemeContext';
import { useProfile } from '../context/ProfileContext';
import { Wizard } from './Wizard';
import { ResumePreview } from './ResumePreview';
import { CreatorCV } from './CreatorCV';
import { ExecutiveCV } from './ExecutiveCV';
import { SpecialistCV } from './SpecialistCV';
import { clsx } from 'clsx';
import { RefreshCcw, Plus, Download, Image as ImageIcon, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';

export const Home = () => {
    const { theme } = useTheme();
    const { profile, setProfile, setInputData } = useProfile();
    const printRef = useRef<HTMLDivElement | null>(null);
    const [isDownloading, setIsDownloading] = useState(false);

    const getThemeBackground = () => {
        if (theme === 'specialist') return '#fcf8fa'; // Soft pinkish-gray for Specialist theme
        if (theme === 'executive') return '#f8fafc';
        return '#fdfaf2'; // Elegant cream for Creator theme
    };

    const handleDownloadPNG = async () => {
        if (!printRef.current) return;
        setIsDownloading(true);
        try {
            const canvas = await html2canvas(printRef.current, { scale: 4, useCORS: true, backgroundColor: getThemeBackground() });
            const data = canvas.toDataURL('image/png');
            const link = document.createElement('a');
            link.href = data;
            link.download = `${profile?.brand_name?.replace(/\s+/g, '_') || 'profile'}_cvless.png`;
            link.click();
        } catch (error) {
            console.error('Error generating image', error);
        } finally {
            setIsDownloading(false);
        }
    };

    const handleDownloadPDF = () => {
        // Native window.print() triggers the browser's PDF engine for 100% Vector & ATS-readable text.
        // We rely on the @media print CSS rules already defined to clean up the UI during print.
        window.print();
    };

    if (!profile) {
        // ...
        return (
            <div className="flex items-center justify-center min-h-screen w-full relative z-10">
                <Wizard />
            </div>
        );
    }

    return (
        <div className={clsx(
            "flex flex-col items-center justify-center min-h-screen pt-10 pb-32 w-full overflow-y-auto print:flex print:items-start print:justify-center print:p-0 print:m-0 print:overflow-hidden print:h-[297mm] print:w-[210mm]",
            theme === 'creator' ? "bg-black/10" : theme === 'specialist' ? "bg-white" : "bg-black/90"
        )}>
            {theme === 'creator' ? (
                <CreatorCV initialProfile={profile} targetRef={printRef} />
            ) : theme === 'executive' ? (
                <ExecutiveCV initialProfile={profile} targetRef={printRef} />
            ) : theme === 'specialist' ? (
                <SpecialistCV initialProfile={profile} targetRef={printRef} />
            ) : (
                <ResumePreview
                    initialProfile={profile}
                    theme={theme}
                    targetRef={printRef}
                    template="modern"
                />
            )}

            {/* Print Only CSS to rigidly enforce a single A4 page limit and colors */}
            <style>{`
                @media print {
                    @page { size: A4 portrait; margin: 0; }
                    html, body {
                        width: 210mm !important;
                        height: 297mm !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        overflow: hidden !important;
                    }
                    * {
                        -webkit-print-color-adjust: exact !important;
                        print-color-adjust: exact !important;
                    }
                    .no-print { display: none !important; }
                }
            `}</style>

            {/* Footer / Contact (Outside of print area) */}
            <div className="mt-8 mb-20 w-full max-w-[210mm] flex flex-col items-center gap-6 no-print relative z-40">
                <div className={clsx("text-[10px] opacity-40 uppercase tracking-widest text-center", theme === 'specialist' ? 'text-black' : 'text-white')}>
                    Generated by CV CopyPaste Logic Core <br />
                    Theme: {theme}
                </div>
            </div>

            {/* Floating Action Menu (Fixed Top Right) */}
            <div className="fixed top-6 right-6 flex flex-col gap-3 z-50 no-print w-40 sm:w-48">
                {(() => {
                    const btnClass = clsx(
                        "w-full px-4 py-3 font-bold uppercase tracking-widest text-[10px] sm:text-xs transition-all flex items-center justify-center gap-2 shadow-lg rounded-md",
                        theme === 'executive' ? "bg-slate-900 text-white hover:bg-slate-800" :
                            theme === 'specialist' ? "bg-[#0360ab] text-white hover:bg-[#024d8a]" :
                                "bg-[#C01C83] text-white hover:bg-[#a5156e] shadow-[4px_4px_0px_#0360ab] border border-transparent"
                    );

                    return (
                        <>
                            {/* NEW PORTFOLIO BUTTON */}
                            <button
                                onClick={() => {
                                    if (window.confirm("Are you sure? This will clear all data.")) {
                                        setInputData(null);
                                        setProfile(null);
                                    }
                                }}
                                className={btnClass}
                            >
                                <Plus className="w-3.5 h-3.5" />
                                <span>New</span>
                            </button>

                            {/* EDIT INFO BUTTON */}
                            <button
                                onClick={() => setProfile(null)} // Keep inputData, just reset view
                                className={btnClass}
                            >
                                <RefreshCcw className="w-3.5 h-3.5" />
                                <span>Edit</span>
                            </button>

                            {/* DOWNLOAD PNG */}
                            <button
                                onClick={handleDownloadPNG}
                                disabled={isDownloading}
                                className={btnClass}
                            >
                                {isDownloading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <ImageIcon className="w-3.5 h-3.5" />}
                                <span>{isDownloading ? '...' : 'PNG'}</span>
                            </button>

                            {/* DOWNLOAD PDF */}
                            <button
                                onClick={handleDownloadPDF}
                                disabled={isDownloading}
                                className={btnClass}
                            >
                                {isDownloading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                                <span>{isDownloading ? 'Gen...' : 'PDF'}</span>
                            </button>
                        </>
                    );
                })()}
            </div>
        </div>
    );
};
